### ISSUE TITLE
PHP 7.1 production support

### ISSUE THREAD

**Issue by Th3Mouk** [italolelis/collections#18]
Hello @italolelis @kieranajp !

Thanks for your work on this lib, I saw you added php 7.1 support last month.

Is it possible to add to tag to use it in production ?

TY

**Comment by italolelis** [comment]
Hi @Th3Mouk,

Thanks for using our library. Yes, I've just created a [new release](https://github.com/italolelis/collections/releases/tag/v7.0.0) with the PHP 7.1 support.

I hope you enjoy it and feel free to send us any feedback 😄
